# -*- coding: utf-8 -*-
"""1.json데이터가공_영어에서한글_박도현.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a26M8ZcEP0zxhQxDo0ee21b8i3Ydwwqq
"""

!pip install datasets
!pip install gdown

import requests
import json
import gdown
import pandas as pd
from datasets import Dataset as dataset
from datasets import load_dataset
import huggingface_hub

# 파일 존재 여부
# import os
# file_path = "C:/Users/ACER/Desktop/json/jsonData/1113_test.json"
# print("파일 존재 여부:", os.path.exists(file_path))


# 로컬로 할 때( 전부다 )
# with open("C:/Users/ACER/Desktop/json/jsonData/1113_tech_valid_set_149403.json", "r", encoding="utf-8") as f:
#     original_data = json.load(f)
# original_data


# 구글 드라이브 JSON 파일 파싱
# url = "https://drive.google.com/uc?export=download&id=10y_1MVl5jUTPAq5FgLZXKojXQX9aolCR"
# response = requests.get(url)
# original_data = json.loads(response.text)
# original_data

url = "https://drive.google.com/uc?export=download&id=10y_1MVl5jUTPAq5FgLZXKojXQX9aolCR"
# 다운로드
gdown.download(url, "data.json", quiet=False)
# JSON 파일 열기
with open("data.json", "r", encoding="utf-8") as f:
    original_data = json.load(f)

# 원본데이터의 키 확인하기
original_data.keys() # 모든 '키' 이름

len(original_data["data"])

original_data["data"]

### 영어에서 한국어로 번역하기
datas = original_data["data"]
# 데이터 가공
alpaca_data_List = []
rowList = []
for i in range(len(datas)):
    if (i < 20):
        eachData = datas[i]
        rowList.append("input을 한글로 번역해줘") # instruction
        rowList.append(eachData["en"]) # input
        rowList.append(f'\"{eachData["ko"]}\"" + " 라고 하네?') # output
        alpaca_data_List.append(rowList)
        rowList = []

# DF화
df = pd.DataFrame(alpaca_data_List, columns=["instruction", "input", "output"])

# 허깅페이스 DataSet에 넣기
# huggingface_hub.login("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") # 로그인1 토큰 값
# huggingface_hub.login("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") # 로그인2 토큰 값
huggingface_hub.login("") # 3-8b 버전

# dataset화
d = dataset.from_pandas(df)
# 허깅페이스 ds저장소 올리기
# d.push_to_hub("imaginaryi/TranslateEnglishToKorean") # r교수님 버전
d.push_to_hub("imaginaryi/TranslateEnglishToKorean_3.8b") # 3-8b 버전

# 반대로 허깅페이스에서 데이터셋 불러오기
# c = load_dataset("imaginaryi/TranslateEnglishToKorean") # 교수님 버전
c = load_dataset("imaginaryi/TranslateEnglishToKorean_3.8b")
c

c.keys()

c["train"][0]

# 불러온 DataSet => DataFrame화
d = c["train"].to_pandas()
# d.to_csv("C:/Users/ACER/Desktop/json/jsonData/20개가공.csv", encoding="ms949", index=False)